- include: configure_service.yml

- name: Include variables
  include_vars: "{{ jboss_datagrid_configuration }}.yml"
  tags:
    - always

- name: Set kernel parameters
  sysctl:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    value: "{{ item.value }}"
    reload: yes
  with_items: "{{ jboss_datagrid_kernel_parameters }}"
  when: jboss_datagrid_kernel_parameters is defined
  tags:
    - jboss_datagrid
    - jboss_datagrid_kernel_parameters

- name: Copy JBoss Data Grip zip file to {{ jboss_datagrid_download_dir }}/{{ jboss_datagrid_zip_file | basename }}
  copy:
    src: "{{ jboss_datagrid_zip_file }}"
    dest: "{{ jboss_datagrid_download_dir }}/{{ jboss_datagrid_zip_file | basename }}"
  tags:
    - jboss_datagrid

- name: Extract JBoss Data Grid
  unarchive:
    src: "{{ jboss_datagrid_download_dir }}/{{ jboss_datagrid_zip_file | basename }}"
    dest: "{{ jboss_datagrid_library_dest }}"
    copy: no
    creates: "{{ jboss_datagrid_home }}/version.txt"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
  register: jboss_datagrid_install
  tags:
    - jboss_datagrid

- name: Copy JBoss Data Grid runtime configuration ({{ jboss_datagrid_runtime_config_file }})
  template:
    src: runtime.conf.j2
    dest: "{{ jboss_datagrid_runtime_config_file }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
  notify: restart jdg
  tags:
    - jboss_datagrid
    - jboss_config

- name: Copy JBoss Data Grid server configuration ({{ jboss_datagrid_configuration }}.xml)
  template:
    src: "{{ jboss_datagrid_configuration }}.xml.j2"
    dest: "{{ jboss_datagrid_home }}/standalone/configuration/{{ jboss_datagrid_configuration }}.xml"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
  notify: restart jdg
  tags:
    - jboss_datagrid
    - jboss_config

- name: Create default JBoss admin user
  command: "{{ jboss_datagrid_home }}/bin/add-user.sh -s -r ManagementRealm -u {{ jboss_datagrid_admin_user }} -p {{ jboss_datagrid_admin_password }}"
  when: jboss_datagrid_install.changed
  tags:
    - jboss_datagrid

- name: Start and enable JBoss Data Grid
  service:
    name: "{{ jboss_datagrid_service_name }}"
    state: started
    enabled: yes
  tags:
    - jboss_datagrid
