- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_distribution_major_version | version_compare('7', '>=')

- name: restart jdg
  service:
    name: "{{ jboss_datagrid_service_name }}"
    state: restarted
